from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 601)
        self.app_title = QtWidgets.QLabel(Dialog)
        self.app_title.setGeometry(QtCore.QRect(10, 10, 541, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setUnderline(True)
        self.app_title.setFont(font)
        self.app_title.setObjectName("app_title")
        self.label_username = QtWidgets.QLabel(Dialog)
        self.label_username.setGeometry(QtCore.QRect(50, 70, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_username.setFont(font)
        self.label_username.setObjectName("label_username")
        self.label_password = QtWidgets.QLabel(Dialog)
        self.label_password.setGeometry(QtCore.QRect(50, 130, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_password.setFont(font)
        self.label_password.setObjectName("label_password")
        self.label_protocolnumber = QtWidgets.QLabel(Dialog)
        self.label_protocolnumber.setGeometry(QtCore.QRect(20, 190, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_protocolnumber.setFont(font)
        self.label_protocolnumber.setObjectName("label_protocolnumber")
        self.cms_vs_mdrive = QtWidgets.QPushButton(Dialog)
        self.cms_vs_mdrive.setGeometry(QtCore.QRect(540, 70, 201, 51))
        self.cms_vs_mdrive.setObjectName("cms_vs_mdrive")
        self.comparison_table = QtWidgets.QTableView(Dialog)
        self.comparison_table.setGeometry(QtCore.QRect(10, 230, 771, 351))
        self.comparison_table.setObjectName("comparison_table")
        self.mdrive_vs_cms = QtWidgets.QPushButton(Dialog)
        self.mdrive_vs_cms.setGeometry(QtCore.QRect(540, 150, 201, 51))
        self.mdrive_vs_cms.setObjectName("mdrive_vs_cms")
        self.password_input = QtWidgets.QLineEdit(Dialog)
        self.password_input.setGeometry(QtCore.QRect(230, 130, 201, 31))
        self.password_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_input.setObjectName("password_input")
        self.username_input = QtWidgets.QLineEdit(Dialog)
        self.username_input.setGeometry(QtCore.QRect(230, 70, 201, 31))
        self.username_input.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.username_input.setObjectName("username_input")
        self.protocol_input = QtWidgets.QLineEdit(Dialog)
        self.protocol_input.setGeometry(QtCore.QRect(230, 190, 201, 31))
        self.protocol_input.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.protocol_input.setObjectName("protocol_input")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.app_title.setText(_translate("Dialog", "SOCS Contact List Comparison Utility"))
        self.label_username.setText(_translate("Dialog", "Username"))
        self.label_password.setText(_translate("Dialog", "Password"))
        self.label_protocolnumber.setText(_translate("Dialog", "Protocol Number"))
        self.cms_vs_mdrive.setText(_translate("Dialog", "CMS CL vs. M Drive CL"))
        self.mdrive_vs_cms.setText(_translate("Dialog", "M Drive CL vs. CMS CL"))

